name: Update stskeygen
on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  refresh-overlay:
    name: Refresh inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update inputs
        run: |
          sh update.sh

      - name: Push commit with updated inputs
        run: |
          git diff --quiet || git commit -a -m "updated stskeygen"
          git push
