name: Update stskeygen
on:
  push:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  refresh-overlay:
    name: Refresh inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update inputs
        run: |
          sh update.sh

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main

      - name: Test build
        run: |
          nix build ".#stskeygen"

      - name: Push commit with updated inputs
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        run: |
          git diff --quiet || git commit -a -m "updated stskeygen"
          git push
